---
title: "ECON 432 Homework 2 Pt. II"
author: "Madelyn Caufield"
date: "`r format(Sys.Date(),'%b %d,%Y')`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    number_sections: yes
    theme: united
    highlight: tango
---

# Part 2: R Excercises 
## Question 1
```{r}
set.seed(123) # for reproducible randomness
runs <- 1
mu.x <- 0
sigma.x <- 0.1

X <- rnorm(runs, mu.x, sigma.x) # the random sample of 5000 observations
head(X)

sum(X >= 0.5)/runs
```

## Question 2
```{r}
set.seed(321)
X <- matrix(rbinom(runs*3,size = 1, prob = 0.5), ncol = 3)
X

Y <- ifelse(X[,1]==1 & X[,2]==1, -3,
            ifelse(X[,1]==0 & X[,2]==0, -1, 2))
head(cbind(X,Y)) 

sum(Y)/runs
```

## Question 3
```{r}
set.seed(321)
X <- matrix(rbinom(runs*3,size = 1, prob = 0.64), ncol = 3)
X

Y <- ifelse(X[,1]==1 & X[,2]==1, -3,
            ifelse(X[,1]==0 & X[,2]==0, -1, 2))
head(cbind(X,Y)) 

sum(Y)/runs
```

## Question 4
```{r}
set.seed(321)
X <- matrix(rbinom(runs*3,size = 1, prob = 0.64), ncol = 3)
X

Y <- ifelse(X[,1]==1 & X[,2]==1, -3,
            ifelse(X[,1]==0 & X[,2]==0, -1, 2))
head(cbind(X,Y)) 

sum(Y>0)/runs
```